@OmnilensScraping_HostAddress = http://localhost:5123

GET {{OmnilensScraping_HostAddress}}/api/scraping/health
Accept: application/json

###

GET {{OmnilensScraping_HostAddress}}/api/scraping/retailers
Accept: application/json

###

GET {{OmnilensScraping_HostAddress}}/api/scraping/retailers/pharmacies
Accept: application/json

###

GET {{OmnilensScraping_HostAddress}}/api/scraping/samples/Unieuro?take=3
Accept: application/json

###

GET {{OmnilensScraping_HostAddress}}/api/scraping/catalog/MediaWorld/count
Accept: application/json

###

GET {{OmnilensScraping_HostAddress}}/api/scraping/catalog/Euronics/parsed?take=2&mode=Auto&maxConcurrency=0
Accept: application/json

###

GET {{OmnilensScraping_HostAddress}}/api/scraping/catalog/Unieuro/concurrency?sampleSize=12&startConcurrency=1&maxConcurrency=8&mode=Auto&successRateThreshold=0.9
Accept: application/json

###

# Amazon IT: crawl discovery page pubblico ampio e salvataggio sitemap organizzato per categorie.
# Per copertura realmente garantita al 100% configura anche una snapshot autorevole in AmazonCatalog.Authoritative*.
POST {{OmnilensScraping_HostAddress}}/api/scraping/catalog/AmazonIt/bootstrap?force=true&take=500
Accept: application/json

###

GET {{OmnilensScraping_HostAddress}}/api/scraping/product?mode=Browser&url=https%3A%2F%2Fwww.amazon.it%2Fdp%2FB081VK1KHV
Accept: application/json

###

GET {{OmnilensScraping_HostAddress}}/api/scraping/catalog/AmazonIt/count
Accept: application/json

###

GET {{OmnilensScraping_HostAddress}}/api/scraping/catalog/Redcare/count
Accept: application/json

###

GET {{OmnilensScraping_HostAddress}}/api/scraping/catalog/Farmacie1000/parsed?take=2&mode=Auto&maxConcurrency=0
Accept: application/json

###

POST {{OmnilensScraping_HostAddress}}/api/scraping/catalog/TopFarmacia/bootstrap?force=true&take=250
Accept: application/json

###

GET {{OmnilensScraping_HostAddress}}/api/scraping/product?mode=Auto&url=https%3A%2F%2Fwww.mediaworld.it%2Fit%2Fproduct%2F_lg-75ur78006lk-tv-led-piatto-75-uhd-4k-105375108.html
Accept: application/json

###

POST {{OmnilensScraping_HostAddress}}/api/scraping/product
Content-Type: application/json

{
  "url": "https://www.unieuro.it/online/iPhone/iPhone-16-128GB-Nero-pidAPLIPHONE16128",
  "mode": "EmbeddedState"
}

###

GET {{OmnilensScraping_HostAddress}}/api/scraping/product?mode=Browser&url=https%3A%2F%2Fwww.euronics.it%2Ftelefonia%2Fcordless-e-telefonia-fissa%2Ftelefoni-fissi%2Fpanasonic---kx-ts560-bianco%2F102000047.html
Accept: application/json
