// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmnilensScraping.Persistence;

#nullable disable

namespace OmnilensScraping.Migrations
{
    [DbContext(typeof(OmnilensDbContext))]
    [Migration("20260409172359_InitialMvpPersistence")]
    partial class InitialMvpPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.AlertDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlertRuleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DeliveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerReason")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.ToTable("alert_deliveries", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CanonicalProductId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOnRestock")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TargetPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalProductId");

                    b.HasIndex("UserId", "CanonicalProductId", "IsActive");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.CanonicalProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalSku")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gtin")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vertical")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Gtin");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("canonical_products", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.CanonicalProductAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributeValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CanonicalProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalProductId", "AttributeName");

                    b.ToTable("canonical_product_attributes", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.ClickEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CanonicalProductId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ClickedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("SourceId", "ClickedAtUtc");

                    b.ToTable("click_events", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VatCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.CompanyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CompanyId", "UserId")
                        .IsUnique();

                    b.ToTable("company_members", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.ConversionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClickEventId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommissionAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ConvertedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalOrderRef")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClickEventId");

                    b.HasIndex("SourceId");

                    b.ToTable("conversion_events", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.PharmacyLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHoursJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("pharmacy_locations", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.PharmacyProductFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveIngredient")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CanonicalProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DosageForm")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageSize")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrengthText")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalProductId")
                        .IsUnique();

                    b.ToTable("pharmacy_product_facts", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.PharmacyReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CanonicalProductId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NreCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReservationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalProductId");

                    b.HasIndex("SourceId");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("pharmacy_reservations", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.PriceHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvailabilityText")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceProductId", "RecordedAtUtc");

                    b.ToTable("price_history", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.ProductOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvailabilityText")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OfferUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceText")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ScrapedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingText")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StockStatus")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceProductId", "IsLatest");

                    b.ToTable("product_offers", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriorityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RetailerCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsCatalogBootstrap")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsLiveScrape")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RetailerCode")
                        .IsUnique();

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.SourceProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvailabilityText")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CanonicalProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gtin")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastScrapedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSuccessAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceProductKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalProductId");

                    b.HasIndex("SourceId", "SourceUrl")
                        .IsUnique();

                    b.ToTable("source_products", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.SourceRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorText")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsSaved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "StartedAtUtc");

                    b.ToTable("source_runs", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.SourceRunLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceRunId", "CreatedAtUtc");

                    b.ToTable("source_run_logs", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.WishlistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CanonicalProductId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalProductId");

                    b.HasIndex("UserId", "CanonicalProductId")
                        .IsUnique();

                    b.ToTable("wishlists", (string)null);
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.AlertDelivery", b =>
                {
                    b.HasOne("OmnilensScraping.Persistence.Entities.AlertRule", "AlertRule")
                        .WithMany("AlertDeliveries")
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.AlertRule", b =>
                {
                    b.HasOne("OmnilensScraping.Persistence.Entities.CanonicalProduct", "CanonicalProduct")
                        .WithMany("AlertRules")
                        .HasForeignKey("CanonicalProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmnilensScraping.Persistence.Entities.AppUser", "User")
                        .WithMany("AlertRules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalProduct");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.CanonicalProductAttribute", b =>
                {
                    b.HasOne("OmnilensScraping.Persistence.Entities.CanonicalProduct", "CanonicalProduct")
                        .WithMany("Attributes")
                        .HasForeignKey("CanonicalProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalProduct");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.ClickEvent", b =>
                {
                    b.HasOne("OmnilensScraping.Persistence.Entities.CanonicalProduct", "CanonicalProduct")
                        .WithMany("ClickEvents")
                        .HasForeignKey("CanonicalProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmnilensScraping.Persistence.Entities.Source", "Source")
                        .WithMany("ClickEvents")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmnilensScraping.Persistence.Entities.AppUser", "User")
                        .WithMany("ClickEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CanonicalProduct");

                    b.Navigation("Source");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.CompanyMember", b =>
                {
                    b.HasOne("OmnilensScraping.Persistence.Entities.Company", "Company")
                        .WithMany("Members")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmnilensScraping.Persistence.Entities.AppUser", "User")
                        .WithMany("CompanyMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.ConversionEvent", b =>
                {
                    b.HasOne("OmnilensScraping.Persistence.Entities.ClickEvent", "ClickEvent")
                        .WithMany("ConversionEvents")
                        .HasForeignKey("ClickEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OmnilensScraping.Persistence.Entities.Source", "Source")
                        .WithMany("ConversionEvents")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClickEvent");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.PharmacyLocation", b =>
                {
                    b.HasOne("OmnilensScraping.Persistence.Entities.Source", "Source")
                        .WithMany("PharmacyLocations")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.PharmacyProductFact", b =>
                {
                    b.HasOne("OmnilensScraping.Persistence.Entities.CanonicalProduct", "CanonicalProduct")
                        .WithOne("PharmacyProductFact")
                        .HasForeignKey("OmnilensScraping.Persistence.Entities.PharmacyProductFact", "CanonicalProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalProduct");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.PharmacyReservation", b =>
                {
                    b.HasOne("OmnilensScraping.Persistence.Entities.CanonicalProduct", "CanonicalProduct")
                        .WithMany("PharmacyReservations")
                        .HasForeignKey("CanonicalProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmnilensScraping.Persistence.Entities.Source", "Source")
                        .WithMany("PharmacyReservations")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmnilensScraping.Persistence.Entities.AppUser", "User")
                        .WithMany("PharmacyReservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalProduct");

                    b.Navigation("Source");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.PriceHistoryEntry", b =>
                {
                    b.HasOne("OmnilensScraping.Persistence.Entities.SourceProduct", "SourceProduct")
                        .WithMany("PriceHistoryEntries")
                        .HasForeignKey("SourceProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceProduct");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.ProductOffer", b =>
                {
                    b.HasOne("OmnilensScraping.Persistence.Entities.SourceProduct", "SourceProduct")
                        .WithMany("ProductOffers")
                        .HasForeignKey("SourceProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceProduct");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.SourceProduct", b =>
                {
                    b.HasOne("OmnilensScraping.Persistence.Entities.CanonicalProduct", "CanonicalProduct")
                        .WithMany("SourceProducts")
                        .HasForeignKey("CanonicalProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OmnilensScraping.Persistence.Entities.Source", "Source")
                        .WithMany("SourceProducts")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalProduct");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.SourceRun", b =>
                {
                    b.HasOne("OmnilensScraping.Persistence.Entities.Source", "Source")
                        .WithMany("SourceRuns")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.SourceRunLog", b =>
                {
                    b.HasOne("OmnilensScraping.Persistence.Entities.SourceRun", "SourceRun")
                        .WithMany("Logs")
                        .HasForeignKey("SourceRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceRun");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.WishlistEntry", b =>
                {
                    b.HasOne("OmnilensScraping.Persistence.Entities.CanonicalProduct", "CanonicalProduct")
                        .WithMany("WishlistEntries")
                        .HasForeignKey("CanonicalProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmnilensScraping.Persistence.Entities.AppUser", "User")
                        .WithMany("WishlistEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalProduct");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.AlertRule", b =>
                {
                    b.Navigation("AlertDeliveries");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.AppUser", b =>
                {
                    b.Navigation("AlertRules");

                    b.Navigation("ClickEvents");

                    b.Navigation("CompanyMemberships");

                    b.Navigation("PharmacyReservations");

                    b.Navigation("WishlistEntries");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.CanonicalProduct", b =>
                {
                    b.Navigation("AlertRules");

                    b.Navigation("Attributes");

                    b.Navigation("ClickEvents");

                    b.Navigation("PharmacyProductFact");

                    b.Navigation("PharmacyReservations");

                    b.Navigation("SourceProducts");

                    b.Navigation("WishlistEntries");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.ClickEvent", b =>
                {
                    b.Navigation("ConversionEvents");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.Company", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.Source", b =>
                {
                    b.Navigation("ClickEvents");

                    b.Navigation("ConversionEvents");

                    b.Navigation("PharmacyLocations");

                    b.Navigation("PharmacyReservations");

                    b.Navigation("SourceProducts");

                    b.Navigation("SourceRuns");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.SourceProduct", b =>
                {
                    b.Navigation("PriceHistoryEntries");

                    b.Navigation("ProductOffers");
                });

            modelBuilder.Entity("OmnilensScraping.Persistence.Entities.SourceRun", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
